### ISSUE TITLE
New metrics plugin for Close.io

### ISSUE THREAD

**Issue by summerville** [segmentio/metrics#7]
Just wanted to let you guys know we built a plugin for [Close.io](http://close.io/):

https://github.com/rarestep/metrics-closeio

For now it provides metrics for:
- Number of leads created
- Number of opportunities created
- Active Opportunities total and expect value

We'll prob add more metrics but just wanted to let other folks know about it who might be interested!

**Comment by ivolo** [comment]
Love it, great plugin! You're documented in the [Plugin list](https://github.com/segmentio/metrics#plugins) my friend.

**Comment by bmiles** [comment]
This is great, thank you. But I couldn't find it on NPM.
